### ISSUE TITLE
List mycete on the Try Matrix Now page

### ISSUE THREAD

**Issue by MilkManzJourDaddy** [qbit/mycete#1]
For more exposure you will want a listing, probably on https://matrix.org/docs/projects/try-matrix-now.html#other •Near the top of that Try Matrix Now page, it instructs to file a PR in https://github.com/matrix-org/matrix-doc •to get your project listed. Good luck.

**Comment by qbit** [comment]
At some point I will. Want to get it feature complete first. - gonna close this until then :D - Thanks for the recommendation!

**Comment by MilkManzJourDaddy** [comment]
Plenty of projects on that page are in Alpha state. But, I assumed since you put the word out on social media linked to Matrix development, that you wanted others aware of the project. And, in Open Source, people often collaborate, even those not closely involved. But it's your call. Anyway, I suggest setting up a Matrix room for your project, which I would join. Good luck.

**Comment by qbit** [comment]
alright, you convinced me :D

**Comment by qbit** [comment]
Added in https://github.com/matrix-org/matrix.org/pull/65
